import { Heading, Container } from '@chakra-ui/react';
import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next App template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container border="2px" marginTop={4}>
        <Heading>Welcome to Next.js!</Heading>
      </Container>
    </div>
  );
}
